name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        node-version: ['20']

    runs-on: ${{ matrix.platform }}

    steps:
    # Avoid issues with Prettier on Windows
    - name: Disable git automatic line ending conversion
      run: git config --global core.autocrlf false

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install and test
      run: |
        npm ci
        npm test
      env:
        CI: true
